[env:rpipico2]
; ============================================================
; VARIANT : WAVESHARE RP2350 TOUCH LCD 2.8
; ============================================================

framework = arduino
; Uses maxgerhardt community platform to access native RP2350 architecture
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
; Fixed: Forces the compilation to use the official Pico 2 layout manifest with BS2 bootloader
board = rpipico2
board_build.core = earlephilhower


monitor_speed = 115200

build_flags =
    -Wall
    -Wextra
    -std=gnu++17

lib_deps =
    adafruit/Adafruit GFX Library@^1.12.6 ;@ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0 ;@ ^1.10.3
    adafruit/Adafruit ILI9341@^1.6.3
    ;paulstoffregen/XPT2046_Touchscreen ; @ ^1.0.7 
    circuitstate/CSE_CST328@^0.0.5    


upload_protocol = picotool
;upload_flags = -f



